name: Python CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          pip install -e .

      - name: Lint with Ruff (matching pre-commit)
        run: |
          ruff check . \
            --config ../pyproject.toml \
            --select E,F,I,UP,A

      - name: Check formatting with Black
        run: black --check --verbose --config ../pyproject.toml .

      - name: Run unit tests
        run: pytest
