name: Python CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          pip install -e .

      - name: Lint with Ruff (auto-fix)
        run: |
          ruff check . --fix --config ../pyproject.toml

          # Fail the build if Ruff made changes
          git diff --exit-code || (echo '❌ Ruff auto-fixed issues. Run `pre-commit run --all-files` and commit the changes.' && exit 1)

      - name: Check formatting with Black
        run: black --check --verbose --config ../pyproject.toml .

      - name: Run unit tests
        run: pytest
