name: Python CI

on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          pip install -e .

      - name: Lint with ruff
        run: |
          ruff check . --select=E9,F63,F7,F82
          ruff check .

      - name: Check formatting with Black
        working-directory: .
        run: black --check --verbose --config=backend/pyproject.toml backend

      - name: Run unit tests
        run: pytest
